### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by chairclr**
Fixes compiler generated warnings

### CODE REVIEW

**Comment by chairclr** [comment]
cc @hakusaro @steviegt6\

**Review by hakusaro — APPROVED** [review]
lgtm~

**Review by steviegt6 — APPROVED** [review]
LGTM (let's get this merged).

**Comment by chairclr** [comment]
This is the issue with Rust project maintainers. They're extremely stuck up and toxic about what kind of code other people write. Even if the pull request just simply fixes some compiler errors, they immediately shut it down because they're too high and mighty to let anyone else touch their code. Something needs to change about this community. They act like they're the gatekeepers of some divine code sanctum, like they were handpicked by the programming gods themselves to dictate what's worthy and what's garbage. Like, who do they think they are? And don't even get me started on their condescending comments. Oh, you dared to suggest a different approach? Well, prepare to be belittled and ridiculed by these self-appointed code overlords. It's like they get off on shooting down any idea that didn't originate from their heads. This isn't how a community should operate. The open-source community thrives off of collaboration and communication, but it's clear that certain Rust developers think they're too good to collaborate with others. It's time for them to step off their high horses and start embracing the contributions of others, or they risk alienating the very community they claim to serve.

**Pull request closed without merging**
